server:
  port: 8080

management:
  metrics:
    export:
      newrelic:
        enabled: true
        api-key: NRII-8CWVcs29z96uPDEAtp73vAmdQIizUgST
        account-id: 3145659
        step: 5s

spring:
  r2dbc:
    url: r2dbc:h2:mem:///db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

type:
  groups:
    p: Guest
    c: Crew
